logging:
  file:
    name: ./var/log/chank-on-tasklet
spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_order_history?useSSL=false&serverTimezone=UTC
    username: root
  sql:
    init:
      schema-locations:
        - classpath:schema.sql
      mode: always
